### ISSUE TITLE
Installing the EarthSim stack

### ISSUE THREAD

**Issue by ocefpaf** [pyviz-topics/EarthSim#168]
First of all thanks for the awesome tools you are developing here.
As more and more Earth scientists try to run the notebooks here they end up asking for the packages to be easier to install.

I noticed that the `dependencies.txt` is a "safe bet" with many packages pinned to versions that are known to work.

However, things like the comment below:

```
# Note 2: Since we started using this version, it's been marked
# "broken" (although downloaded >50k times).  However, newest version
# requires boost 1.67.0, while c-f was previously pinned to 1.66.0
# (and 1.66.0 was used for erdc packages). Should be able to revert to
# conda-forge when we update to boost-cpp 1.67.0.
```

worries me. As the conda-forge maintainer of most of those packages I can say that the reason to move packages to the `broken` label is b/c they are no longer compatible with the rest of the dependency stack. We don't remove them for the sake of reproducibility but we do not recommend people to keep using them as it is easy to create a broken environment.

At the moment I just gave a demo of the tools here with the following env:

```yaml
name: mapping
channels:
  - conda-forge
  - pyviz/label/earthsim
  - defaults
dependencies:
  - basemap
  - bokeh
  - cartopy
  - fiona
  - folium
  - geopandas
  - gridgeo
  - ipyleaflet
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - palettable
  - python=3.6
  - rasterio
  - shapely
  - xarray
  - xlrd
  # earthsim
  - colorcet
  - datashader
  - descartes
  - earthsim
  - filigree
  - geoviews
  - gssha
  - gsshapy
  - holoviews
  - lancet
  - nodejs
  - opencv
  - param
  - parambokeh
  - paramnb
  - pyct
  - quest
  - scikit-image
  - x264
```

No pinned dependencies version or channels. Everything worked just fine. My plan is to slowly add the packages from the `pyviz/label/earthsim` channel to `conda-forge` to reduce the chance of [binary incompatibility due to channel mixing](https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels).

Is that something the devs here want to participate? Do you want to be added as maintainers of the `conda-forge` version of these packages? (We already have some of those BTW.)

Also, feel free to open issues on the `conda-forge` feedstocks when something is broken. We would like to get those fixed!
